export const GET_ERRORS = 'GET_ERRORS'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const GET_BOOKS = 'GET_BOOKS'
export const ISSUE_BOOK = 'ISSUE_BOOK'
export const USER_BOOK = 'USER_BOOK'
export const RETURN_BOOK = 'RETURN_BOOK'
